### ISSUE TITLE
Docker pull failed

### ISSUE THREAD

**Issue by dazhymov** [padlik/oracle-12c#5]
### Preset:
macOS: Sequoia 15.0.1
chip: M2
### Issue
I try to run this image

> docker run -d --name oracle12c \
--privileged -v /data/oracle-12c:/u01/app/oracle \
-p 8080:8080 -p 8066:1521 absolutapps/oracle-12c-ee

but failed. 

> latest: Pulling from absolutapps/oracle-12c-ee
docker: [DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of docker.io/absolutapps/oracle-12c-ee:latest to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/.

Can you help with it?

**Comment by ppronko-sugarcrm** [comment]
Unfortunately i cannot support this image anymore because of licensing restrictions.
Please use the official Oracle github docker repository [Link](https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance).
